/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalystRouteImport } from './routes/analyst'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as RfqIdRouteImport } from './routes/rfq.$id'
import { Route as RfqNewRouteImport } from './routes/rfq.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRoute = AnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIdRoute = RfqIdRouteImport.update({
  id: '/rfq/$id',
  path: '/rfq/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqNewRoute = RfqNewRouteImport.update({
  id: '/rfq/new',
  path: '/rfq/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/compare': typeof CompareRoute
  '/inbox': typeof InboxRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/compare': typeof CompareRoute
  '/inbox': typeof InboxRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/compare': typeof CompareRoute
  '/inbox': typeof InboxRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyst' | '/compare' | '/inbox' | '/rfq/$id' | '/rfq/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyst' | '/compare' | '/inbox' | '/rfq/$id' | '/rfq/new'
  id:
    | '__root__'
    | '/'
    | '/analyst'
    | '/compare'
    | '/inbox'
    | '/rfq/$id'
    | '/rfq/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystRoute: typeof AnalystRoute
  CompareRoute: typeof CompareRoute
  InboxRoute: typeof InboxRoute
  RfqIdRoute: typeof RfqIdRoute
  RfqNewRoute: typeof RfqNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/$id': {
      id: '/rfq/$id'
      path: '/rfq/$id'
      fullPath: '/rfq/$id'
      preLoaderRoute: typeof RfqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/new': {
      id: '/rfq/new'
      path: '/rfq/new'
      fullPath: '/rfq/new'
      preLoaderRoute: typeof RfqNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystRoute: AnalystRoute,
  CompareRoute: CompareRoute,
  InboxRoute: InboxRoute,
  RfqIdRoute: RfqIdRoute,
  RfqNewRoute: RfqNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
